name: Build and Push to GHCR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 允许推送镜像到 GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录到 GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # GitHub 用户名
          password: ${{ secrets.GITHUB_TOKEN }}  # 自动生成的令牌，无需手动配置

      # 构建并推送镜像
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            # 将仓库所有者名称强制转为小写
            ghcr.io/${{ toLower(github.repository_owner) }}/dual-ai-chat:latest
            ghcr.io/${{ toLower(github.repository_owner) }}/dual-ai-chat:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
